name: customer_app
description: "Do4U Customer Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  go_router: ^12.1.3
  dio: ^5.4.0
  firebase_core: ^2.24.2
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  pin_code_fields: ^8.0.1
  models:
    path: ../../packages/models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
